#!/usr/bin/python3

import argparse
import pymysql.cursors
import json

#Парсим json из файла
parser = argparse.ArgumentParser()
parser.add_argument('file', type=argparse.FileType('r'))
args = parser.parse_args()

with args.file as file:
    json_pars = args.file.read()
    json_file = json.loads(json_pars)
    json_tran_id = json_file["receiptData"]["TransactionID"]

#Выводим на экран данные json файла
#print(json_file["receiptData"]["TransactionID"])

#Подключени к базе данных
connection = pymysql.connect(host='localhost',
                             user='root',
                             password='qaz123',                             
                             db='test',
                             charset='utf8mb4',
                             cursorclass=pymysql.cursors.DictCursor)

#Функция для добавления данных из ДЖСОН в БД
def add(json_file):
    try:
        with connection.cursor() as cursor:
            cursor.execute("INSERT INTO test_table (transaction_id) VALUES (%s)", json_file)
            connection.commit()
    finally:
        connection.close()
#Использование функции
#add(json_file["receiptData"]["TransactionID"])

#Проверяем, есть ли транзакция с переданным ID в базе.
#Если есть - программа возвращает сообщение и заканчивает работу.
#Если нет - данные из json сохраняются в базу данных.

def check_transaction():

    with connection.cursor() as cursor:
        cursor.execute('SELECT transaction_id FROM test_table WHERE transaction_id = %s', json_tran_id)
        row = cursor.fetchall()

    if json_tran_id in str(row):
        print('This transaction already exists')
        quit()
    else:
        add(json_tran_id)

check_transaction()