#!/usr/bin/python3

import pymysql.cursors

connection = pymysql.connect(host='localhost',
                             user='root',
                             password='qaz123',                             
                             db='test',
                             charset='utf8mb4',
                             cursorclass=pymysql.cursors.DictCursor)

print("Connect Succesfull!")

try:
    with connection.cursor() as cursor:

        #SQL
        sql = "SELECT * FROM test_table"

        #Выполнить команду запроса
        cursor.execute(sql)

        print("cursor.description: ", cursor.description)

        print()

        for row in cursor:
            print(row)

finally:
    #Закрыть соединение
    connection.close()