#!/usr/bin/python3

import sys
import json
import argparse
from pprint import pprint

def createParser():
    parser = argparse.ArgumentParser()
    parser.add_argument ('name', type=open)

    return parser


if __name__ == '__main__':
    parser = createParser()
    namespace = parser.parse_args()

    with open('purchase.json', 'r', encoding='utf-8') as f:
        text = json.load(f)
        pprint(text)