#!/usr/bin/python3

import argparse
import pymysql.cursors

#Подключени к базе данных
connection = pymysql.connect(host='localhost',
                             user='root',
                             password='qaz123',                             
                             db='test',
                             charset='utf8mb4',
                             cursorclass=pymysql.cursors.DictCursor)

#Парсим json из файла
parser = argparse.ArgumentParser()
parser.add_argument('file', type=argparse.FileType('r'))
args = parser.parse_args()

print(args.file.readlines())